### ISSUE TITLE
Does tab completion work?

### ISSUE THREAD

**Issue by fperez** [takluyver/ubit_kernel#1]
I see that 41549f2e4 added tab completion, but it's not working for me in the notebook (4.3.0).  Am I doing something wrong? 

Happy to help fix it, once I get a bit out from under the backlog...

**Comment by takluyver** [comment]
I can't currently get it working to test, but if you installed from PyPI, I think the tab completion is not yet in a release.

**Comment by fperez** [comment]
Ah, no worries then! Yes, I did install from pypi.  Will reinstall from a source checkout, thanks!

Would you like a bit of help on this one? Might become my weekends project :)

**Comment by takluyver** [comment]
I've just pushed a new release to PyPI, so if you install again, tab completion should be available. It only completes names in the main namespace and attribute access, but that helps a lot.

**Comment by fperez** [comment]
Excellent, confirming that the namespace completion works, just tested it. Thanks!
